### ISSUE TITLE
Pydub not working on windows due to tempfile permissions

### ISSUE THREAD

**Issue by SebastienPeillet** [hytechimaging/sammo-boat#122]
```
from pathlib import Path
from pydub import AudioSegment
from pydub.playback import play

filename = Path("C:/Users/Sébastien PEILLET/sammo_data") / "observation_sound_recording_20211215_141801.wav"
sound = AudioSegment.from_wav(filename)
play(sound)
        


Traceback (most recent call last):
  File "", line 8, in 
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pydub\playback.py", line 71, in play
    _play_with_ffplay(audio_segment)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pydub\playback.py", line 15, in _play_with_ffplay
    seg.export(f.name, "wav")
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pydub\audio_segment.py", line 867, in export
    out_f, _ = _fd_or_path_or_tempfile(out_f, 'wb+')
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\SBASTI~1\\AppData\\Local\\Temp\\tmptus6sq3y.wav'
```

**Comment by pblottiere** [comment]
`soundfile` is used instead of `pydub`
